title: 量子コンピューティング・ワークブック
author: 東京大学素粒子物理国際研究センター
logo: ../images/icepp.jpg

execute:
  execute_notebooks: "auto"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

latex:
  latex_documents:
    targetname: qc-workbook_jp.tex

html:
  favicon: ../images/favicon_icepp.png
  use_repository_button: true

repository:
  url: "https://github.com/UTokyo-ICEPP/qc-workbook"
  book_path: source/jp
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebelab: true

sphinx:
  config:
    myst_footnote_transition: false
    myst_enable_extensions:
      - dollarmath
      - smartquotes