title: 量子コンピューティング・ワークブック
author: 東京大学素粒子物理国際研究センター
logo: ../images/icepp.jpg

latex:
  latex_documents:
    targetname: qc-workbook_jp.tex

repository:
  url: "https://github.com/UTokyo-ICEPP/qc-workbook"
  book_path: source/jp
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebelab: true
