title: Quantum Computing Workbook
author: ICEPP, The University of Tokyo
logo: ../images/icepp.png

latex:
  latex_documents:
    targetname: qc-workbook_en.tex

html:
  favicon: ../images/favicon_icepp.png
  use_repository_button: true

repository:
  url: "https://github.com/UTokyo-ICEPP/qc-workbook"
  book_path: source/en
  branch: master

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebelab: true
